# Generated by Django 4.0.5 on 2022-06-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(max_length=20)),
                ('department_code', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.IntegerField(max_length=20)),
                ('faculty_name', models.CharField(max_length=100)),
                ('faculty_type', models.CharField(max_length=100)),
                ('department_id', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(max_length=20)),
                ('student_regno', models.IntegerField(max_length=20)),
                ('student_address', models.CharField(max_length=100)),
                ('faculty_type', models.CharField(max_length=100)),
                ('department_id', models.IntegerField(max_length=20)),
            ],
        ),
    ]
