# Generated by Django 4.0.5 on 2022-06-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='faculty_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='department_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_regno',
            field=models.CharField(max_length=30),
        ),
    ]
