# Generated by Django 4.0.5 on 2022-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_department_department_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=3000)),
                ('material_sem', models.IntegerField()),
                ('material_batch', models.CharField(max_length=20)),
                ('material_subject', models.CharField(max_length=20)),
                ('material_type', models.CharField(max_length=20)),
            ],
        ),
    ]
